spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:ittae}
    username: ${POSTGRES_USER:ittae_user}
    password: ${POSTGRES_PASSWORD:ittae_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis configuration (optional)
  data:
    redis:
      host: redis
      port: 6379
      password: # No password by default
      timeout: 2000ms

# Security
jwt:
  secret: ${JWT_SECRET:default-secret-key}
  expiration: 86400000 # 24 hours

# AI Configuration
gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-1.5-flash

# MCP Configuration
mcp:
  service-url: http://mcp:8000

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.ittae: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
  file:
    name: /app/logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api
